email = "suvid.datta@gmail.com"
github = "https://github.com/Amazeryogo"
reddit = "https://www.reddit.com/user/Amazeryogo"
twitch = "https://www.twitch.tv/amazeryogo29"
youtube = "https://www.youtube.com/channel/UCTqxrChE3FXhy_yJg93pX4A"
spotify = "https://open.spotify.com/user/p46kuy15wgr1aa8x132asq9o4?si=65c67f78ee5e4e81"